export const kpisAccidentes = [
  {
    id: 1,
    label: "ACCIDENTES\nDEL AÑO",
    value: "14",
    sub: "2 incapacitantes",
    icon: "fa-person-falling-burst",
    iconBg: "bg-[#e6f0ff]",
    iconColor: "text-brand",
  },
  {
    id: 2,
    label: "CASOS",
    value: "58",
    sub: "ratio 4.1 por accidente",
    icon: "fa-file-lines",
    iconBg: "bg-risk-salmon/15",
    iconColor: "text-risk-salmon",
  },
  {
    id: 3,
    label: "DÍAS\nPERDIDOS",
    value: "94",
    sub: "índice de severidad 48",
    icon: "fa-briefcase",
    iconBg: "bg-success/15",
    iconColor: "text-success-dark",
  },
  {
    id: 4,
    label: "ENF. OCUPACIONALES EN CALIFICACIÓN",
    value: "3",
    sub: "hipoacusia y neumoconiosis",
    icon: "fa-file-shield",
    iconBg: "bg-risk-red/10",
    iconColor: "text-risk-red",
  },
] as const;

export const registroEventos = [
  {
    id: 1,
    tipo: "Accidente",
    codigo: "ACC-2026-014",
    fecha: "2026-06-12",
    trabajador: "Jorge Ttito Ayala",
    area: "Mantenimiento",
    severidad: "Incapacitante",
    dias: "12",
    causa: "Falta de bloqueo de energía (LOTO)",
    estado: "INVESTIGADO",
    estadoClass: "bg-risk-salmon/15 text-risk-salmon",
  },
  {
    id: 2,
    tipo: "Accidente",
    codigo: "ACC-2026-011",
    fecha: "2026-04-30",
    trabajador: "Carlos Bravo Ríos",
    area: "Mina",
    severidad: "Leve",
    dias: "2",
    causa: "Superficie irregular sin señalizar",
    estado: "CERRADO",
    estadoClass: "bg-success/15 text-success-dark",
  },
  {
    id: 3,
    tipo: "Incidente",
    codigo: "INC-2026-058",
    fecha: "2026-06-20",
    trabajador: "Pedro Salas Ninahuanca",
    area: "Acarreo",
    severidad: "Sin lesión",
    dias: "0",
    causa: "Fatiga por turno extendido",
    estado: "EN ANÁLISIS",
    estadoClass: "bg-violet/15 text-violet",
  },
  {
    id: 4,
    tipo: "Incidente",
    codigo: "INC-2026-052",
    fecha: "2026-05-27",
    trabajador: "Víctor Anco Flores",
    area: "Chancado",
    severidad: "Sin lesión",
    dias: "0",
    causa: "Fuga de polvo por sello dañado",
    estado: "CERRADO",
    estadoClass: "bg-success/15 text-success-dark",
  },
  {
    id: 5,
    tipo: "Enf. ocupacional",
    codigo: "EO-2026-003",
    fecha: "2026-03-15",
    trabajador: "Luis Quispe Ramos",
    area: "Mina",
    severidad: "Hipoacusia",
    dias: "0",
    causa: "Exposición acumulada a ruido > LMP",
    estado: "EN ANÁLISIS",
    estadoClass: "bg-violet/15 text-violet",
  },
] as const;
