export const kpisCapacitaciones = [
  {
    id: 1,
    label: "CAPACITACIONES\nDEL AÑO",
    value: "5",
    sub: "2 cerradas · 2 en curso",
    icon: "fa-file-circle-check",
    iconBg: "bg-[#e6f0ff]",
    iconColor: "text-brand",
  },
  {
    id: 2,
    label: "HORAS\nHOMBRE",
    value: "4,182",
    sub: "promedio 3.2 h por trabajador",
    icon: "fa-briefcase",
    iconBg: "bg-risk-salmon/15",
    iconColor: "text-risk-salmon",
  },
  {
    id: 3,
    label: "ASISTENCIA\nGLOBAL",
    value: "79%",
    sub: "meta 90%",
    icon: "fa-chart-line",
    iconBg: "bg-success/15",
    iconColor: "text-success-dark",
  },
  {
    id: 4,
    label: "CONVOCADOS\nPENDIENTES",
    value: "332",
    sub: "por reprogramar",
    icon: "fa-user-clock",
    iconBg: "bg-risk-red/10",
    iconColor: "text-risk-red",
  },
] as const;

export const calendarioCapacitaciones = [
  {
    id: 1,
    tema: "Uso correcto de protección auditiva",
    modalidad: "Presencial",
    grupo: ["G2", "G3"],
    fecha: "2026-05-15",
    asistencia: "191 / 218",
    cumplimiento: 88,
    estado: "CERRADO",
  },
  {
    id: 2,
    tema: "Protección respiratoria y prueba de ajuste",
    modalidad: "Presencial",
    grupo: ["G2", "G3"],
    fecha: "2026-06-04",
    asistencia: "132 / 198",
    cumplimiento: 67,
    estado: "EN CURSO",
  },
  {
    id: 3,
    tema: "Higiene postural y manejo de cargas",
    modalidad: "Mixta",
    grupo: ["Todos"],
    fecha: "2026-04-18",
    asistencia: "512 / 640",
    cumplimiento: 80,
    estado: "CERRADO",
  },
  {
    id: 4,
    tema: "Gestión de fatiga y sueño en turnos",
    modalidad: "Virtual",
    grupo: ["Todos"],
    fecha: "2026-06-25",
    asistencia: "244 / 421",
    cumplimiento: 58,
    estado: "EN CURSO",
  },
  {
    id: 5,
    tema: "Primeros auxilios y respuesta médica",
    modalidad: "Presencial",
    grupo: ["Brigadistas"],
    fecha: "2026-08-28",
    asistencia: "0 / 60",
    cumplimiento: 0,
    estado: "PROGRAMADO",
  },
] as const;
