export const contratistas = [
  {
    id: 1,
    slug: "vigilancia-andina",
    empresa: "Vigilancia Andina",
    ruc: "20605277415",
    servicio: "Seguridad",
    sede: "Condorcocha",
    trabajadores: 250,
    emoVigente: "92%",
    actualizacion: "15/08/2026",
    estado: "ACTIVO" as const,
  },
  {
    id: 2,
    slug: "myh-group",
    empresa: "MyH Group",
    ruc: "20605277415",
    servicio: "Servicios Generales",
    sede: "Conchán",
    trabajadores: 150,
    emoVigente: "88%",
    actualizacion: "15/08/2026",
    estado: "ACTIVO" as const,
  },
  {
    id: 3,
    slug: "haug",
    empresa: "HAUG",
    ruc: "20605277415",
    servicio: "Mecánica",
    sede: "Villarán",
    trabajadores: 130,
    emoVigente: "61%",
    actualizacion: "15/08/2026",
    estado: "ACTIVO" as const,
  },
  {
    id: 4,
    slug: "san-martin-cgsa",
    empresa: "San Martin CGSA",
    ruc: "20605277415",
    servicio: "Perforación",
    sede: "Condorcocha",
    trabajadores: 260,
    emoVigente: "79%",
    actualizacion: "15/08/2026",
    estado: "ACTIVO" as const,
  },
  {
    id: 5,
    slug: "ecotec",
    empresa: "ECOTEC",
    ruc: "20605277415",
    servicio: "Mantenimiento",
    sede: "Atocongo",
    trabajadores: 87,
    emoVigente: "95%",
    actualizacion: "15/08/2026",
    estado: "ACTIVO" as const,
  },
] as const;
