export const kpisEmos = [
  {
    id: 1,
    label: "TRABAJADORES\nCARGADOS",
    value: "1,284",
    sub: "última carga: 12 ago 2026",
    icon: "fa-users-gear",
    iconBg: "bg-[#e6f0ff]",
    iconColor: "text-brand",
  },
  {
    id: 2,
    label: "LEGAJOS\nDIGITALIZADOS",
    value: "1,142",
    sub: "89% de la población",
    icon: "fa-file-circle-plus",
    iconBg: "bg-[#e0f8ec]",
    iconColor: "text-success-dark",
  },
  {
    id: 3,
    label: "EMOS POR VENCER\n(60 DÍAS)",
    value: "117",
    sub: "",
    icon: "fa-file-shield",
    iconBg: "bg-risk-salmon/15",
    iconColor: "text-risk-salmon",
  },
  {
    id: 4,
    label: "APTITUDES CON\nRESTRICCIÓN",
    value: "146",
    sub: "incluye 9 no aptos",
    icon: "fa-person-circle-exclamation",
    iconBg: "bg-risk-red/10",
    iconColor: "text-risk-red",
  },
] as const;

export const matrizEmos = [
  {
    id: 1,
    trabajador: "Luis Quispe Ramos",
    dni: "DNI 4412896",
    puesto: "Operador de perforadora",
    sede: "Condorcocha",
    antiguedad: "10a 5m",
    ingreso: "2016-03-14",
    emo: "Periódico",
    emoFecha: "2026-05-12",
    aptitud: "APTO CON\nRESTRICCIONES",
    hallazgos: ["Hipoacusia neurosensorial bilateral", "IMC 33.1"],
    hallazgosColor: "text-risk-red",
    factores: "Ruido / Vibración / Polvo",
    grupo: "G3" as const,
  },
  {
    id: 2,
    trabajador: "Maria Chávez Loayza",
    dni: "DNI 52698874",
    puesto: "Analista de laboratorio",
    sede: "Condorcocha",
    antiguedad: "10a 5m",
    ingreso: "2016-03-14",
    emo: "Periódico",
    emoFecha: "2026-05-12",
    aptitud: "APTO",
    hallazgos: ["Espirometría restrictiva leve"],
    hallazgosColor: "text-risk-salmon",
    factores: "Químicos / Ergonómico",
    grupo: "G2" as const,
  },
  {
    id: 3,
    trabajador: "Jorge Tito Ayala",
    dni: "DNI 75968399",
    puesto: "Soldador",
    sede: "Condorcocha",
    antiguedad: "10a 5m",
    ingreso: "2016-03-14",
    emo: "Periódico",
    emoFecha: "2026-05-12",
    aptitud: "OBSERVADO",
    hallazgos: ["Pterigión OD", "Dermatitis de contacto"],
    hallazgosColor: "text-risk-red",
    factores: "Radiación UV / Humos metálicos",
    grupo: "G3" as const,
  },
  {
    id: 4,
    trabajador: "Rosa Huamán Ccapa",
    dni: "DNI 65897785",
    puesto: "Asistente administrativa",
    sede: "Sede Lima",
    antiguedad: "3a 6m",
    ingreso: "2023-02-13",
    emo: "Ingreso",
    emoFecha: "2026-02-13",
    aptitud: "APTO",
    hallazgos: ["Sin hallazgos"],
    hallazgosColor: "text-text-secondary",
    factores: "Ergonómico /Psicosocial",
    grupo: "G1" as const,
  },
] as const;
