export const kpisMatriz = [
  {
    id: 1,
    label: "PELIGROS\nIDENTIFICADOS",
    value: "7",
    sub: "en 7 procesos críticos",
    icon: "fa-person-falling-burst",
    iconBg: "bg-[#e6f0ff]",
    iconColor: "text-brand",
  },
  {
    id: 2,
    label: "RIESGOS CRÍTICOS /\nALTOS",
    value: "4",
    sub: "requieren control inmediato",
    icon: "fa-triangle-exclamation",
    iconBg: "bg-risk-salmon/15",
    iconColor: "text-risk-salmon",
  },
  {
    id: 3,
    label: "TRABAJADORES\nEXUESTOS",
    value: "1,343",
    sub: "con exposición acumulada",
    icon: "fa-people-group",
    iconBg: "bg-success/15",
    iconColor: "text-success-dark",
  },
  {
    id: 4,
    label: "RIESGOS CON\nPROGRAMA ACTIVO",
    value: "7 / 7",
    sub: "cobertura total",
    icon: "fa-user-shield",
    iconBg: "bg-risk-red/10",
    iconColor: "text-risk-red",
  },
] as const;

export const matrizIperc = [
  {
    id: 1,
    proceso: "Perforación y voladura",
    peligro: "Ruido continuo > 90 dBAH",
    riesgo: "Hipoacusia inducida por ruido",
    expuestos: "218",
    prob: "Alta",
    sev: "Alta",
    nivel: "CRITICO",
    nivelClass: "bg-risk-red/15 text-risk-red",
    control: "Protección auditiva doble + rotación",
    programa: "Conservación auditiva",
  },
  {
    id: 2,
    proceso: "Chancado y molienda",
    peligro: "Polvo respirable con sílice",
    riesgo: "Neumoconiosis / silicosis",
    expuestos: "164",
    prob: "Media",
    sev: "Alta",
    nivel: "ALTO",
    nivelClass: "bg-risk-salmon/15 text-risk-salmon",
    control: "Supresión de polvo + respirador P100",
    programa: "Protección respiratoria",
  },
  {
    id: 3,
    proceso: "Transporte de mineral",
    peligro: "Vibración cuerpo entero",
    riesgo: "Trastorno musculoesquelético lumbar",
    expuestos: "132",
    prob: "Media",
    sev: "Media",
    nivel: "MODERADO",
    nivelClass: "bg-success/15 text-success-dark",
    control: "Asientos amortiguados + pausas",
    programa: "Ergonomía",
  },
  {
    id: 4,
    proceso: "Mantenimiento mecánico",
    peligro: "Manipulación manual de cargas",
    riesgo: "Lumbalgia ocupacional",
    expuestos: "98",
    prob: "Alta",
    sev: "Media",
    nivel: "ALTO",
    nivelClass: "bg-risk-salmon/15 text-risk-salmon",
    control: "Ayudas mecánicas + escuela de espalda",
    programa: "Ergonomía",
  },
  {
    id: 5,
    proceso: "Laboratorio químico",
    peligro: "Vapores de ácidos",
    riesgo: "Irritación / neumonitis química",
    expuestos: "34",
    prob: "Baja",
    sev: "Alta",
    nivel: "MODERADO",
    nivelClass: "bg-success/15 text-success-dark",
    control: "Campana extractora + monitoreo biológico",
    programa: "Protección respiratoria",
  },
  {
    id: 6,
    proceso: "Operación en altura geográfica",
    peligro: "Hipoxia hipobárica",
    riesgo: "Mal de altura crónico",
    expuestos: "276",
    prob: "Media",
    sev: "Media",
    nivel: "MODERADO",
    nivelClass: "bg-success/15 text-success-dark",
    control: "Aclimatación + tamizaje cardiológico",
    programa: "Cardiometabólico",
  },
] as const;
