// ──────────────────────────────────────────────
// COMPRAS - REGISTRO DE MEDICAMENTOS
// ──────────────────────────────────────────────
export interface Medicamento {
  codigoInterno: string;
  nombreProducto: string;
  laboratorio: string;
  principioActivo: string;
  presentacion: string;
  tipoMedicamento: string;
  codigoProductoDigemid: string;
  codigoGenericoDigemid: string;
  registroSanitario: string;
  requiereReceta: boolean;
  costoProducto: number;
  precioUnidad: number;
  precioBlister: number;
  precioCaja: number;
}

export const medicamentosCatalogoData: Medicamento[] = [
  {
    codigoInterno: "MED-00102",
    nombreProducto: "PARACETAMOL 500 MG TABLETA",
    laboratorio: "MEDIFARMA",
    principioActivo: "PARACETAMOL",
    presentacion: "TABLETA",
    tipoMedicamento: "GENERICO",
    codigoProductoDigemid: "DIG-10245",
    codigoGenericoDigemid: "GEN-00231",
    registroSanitario: "RS-EE-12345",
    requiereReceta: false,
    costoProducto: 0.25,
    precioUnidad: 0.35,
    precioBlister: 3.5,
    precioCaja: 25.0,
  },
  {
    codigoInterno: "MED-00105",
    nombreProducto: "IBUPROFENO 400 MG TABLETA",
    laboratorio: "GENFAR",
    principioActivo: "IBUPROFENO",
    presentacion: "TABLETA RECUBIERTA",
    tipoMedicamento: "GENERICO",
    codigoProductoDigemid: "DIG-10311",
    codigoGenericoDigemid: "GEN-00245",
    registroSanitario: "RS-EE-12402",
    requiereReceta: false,
    costoProducto: 0.3,
    precioUnidad: 0.45,
    precioBlister: 4.5,
    precioCaja: 32.0,
  },
  {
    codigoInterno: "MED-00140",
    nombreProducto: "AMOXICILINA 500 MG CÁPSULA",
    laboratorio: "HERSIL",
    principioActivo: "AMOXICILINA",
    presentacion: "CÁPSULA",
    tipoMedicamento: "DE MARCA",
    codigoProductoDigemid: "DIG-10488",
    codigoGenericoDigemid: "GEN-00267",
    registroSanitario: "RS-EE-12518",
    requiereReceta: true,
    costoProducto: 0.45,
    precioUnidad: 0.65,
    precioBlister: 6.5,
    precioCaja: 48.0,
  },
  {
    codigoInterno: "MED-00210",
    nombreProducto: "OMEPRAZOL 20 MG CÁPSULA",
    laboratorio: "MEDIFARMA",
    principioActivo: "OMEPRAZOL",
    presentacion: "CÁPSULA",
    tipoMedicamento: "GENERICO",
    codigoProductoDigemid: "DIG-10533",
    codigoGenericoDigemid: "GEN-00288",
    registroSanitario: "RS-EE-12604",
    requiereReceta: true,
    costoProducto: 0.4,
    precioUnidad: 0.55,
    precioBlister: 5.5,
    precioCaja: 40.0,
  },
  {
    codigoInterno: "MED-00330",
    nombreProducto: "LORATADINA 10 MG TABLETA",
    laboratorio: "GENFAR",
    principioActivo: "LORATADINA",
    presentacion: "TABLETA",
    tipoMedicamento: "GENERICO",
    codigoProductoDigemid: "DIG-10602",
    codigoGenericoDigemid: "GEN-00301",
    registroSanitario: "RS-EE-12675",
    requiereReceta: false,
    costoProducto: 0.2,
    precioUnidad: 0.3,
    precioBlister: 3.0,
    precioCaja: 21.0,
  },
  {
    codigoInterno: "MED-00412",
    nombreProducto: "AZITROMICINA 500 MG TABLETA RECUBIERTA",
    laboratorio: "PFIZER",
    principioActivo: "AZITROMICINA",
    presentacion: "TABLETA RECUBIERTA",
    tipoMedicamento: "DE MARCA",
    codigoProductoDigemid: "DIG-10745",
    codigoGenericoDigemid: "GEN-00322",
    registroSanitario: "RS-EE-12741",
    requiereReceta: true,
    costoProducto: 1.5,
    precioUnidad: 2.1,
    precioBlister: 21.0,
    precioCaja: 155.0,
  },
  {
    codigoInterno: "MED-00508",
    nombreProducto: "CLORFENAMINA 4 MG TABLETA",
    laboratorio: "FARMINDUSTRIA",
    principioActivo: "CLORFENAMINA",
    presentacion: "TABLETA",
    tipoMedicamento: "GENERICO",
    codigoProductoDigemid: "DIG-10812",
    codigoGenericoDigemid: "GEN-00340",
    registroSanitario: "RS-EE-12803",
    requiereReceta: false,
    costoProducto: 0.15,
    precioUnidad: 0.22,
    precioBlister: 2.2,
    precioCaja: 15.5,
  },
  {
    codigoInterno: "MED-00620",
    nombreProducto: "DEXAMETASONA 4 MG / 2 ML INYECTABLE",
    laboratorio: "QUÍMICA SUIZA",
    principioActivo: "DEXAMETASONA",
    presentacion: "INYECCIÓN",
    tipoMedicamento: "DE MARCA",
    codigoProductoDigemid: "DIG-10904",
    codigoGenericoDigemid: "GEN-00358",
    registroSanitario: "RS-EE-12877",
    requiereReceta: true,
    costoProducto: 1.1,
    precioUnidad: 1.6,
    precioBlister: 0,
    precioCaja: 118.0,
  },
];

export const laboratoriosMedicamento: string[] = [
  "AC FARMACEUTICA",
  "ABBOTT",
  "ASTRAZENECA",
  "BAGO",
  "BAYER",
  "BOEHRINGER",
  "FARMINDUSTRIA",
  "GENFAR",
  "GLAXOSMITHKLINE",
  "GSK",
  "HERMES",
  "HERSIL",
  "INDUQUÍMICA",
  "INNOVA",
  "JANSSEN",
  "LASANTE",
  "MEDIFARMA",
  "MERCK",
  "NOVARTIS",
  "PFIZER",
  "PORTUGAL",
  "QUÍMICA SUIZA",
  "TEVA",
];

export const presentacionesMedicamento: string[] = [
  "AEROSOL",
  "CÁPSULA",
  "CREMA",
  "GEL",
  "INYECCIÓN",
  "JARABE",
  "ÓVULO",
  "POLVO",
  "SUPOSITORIO",
  "SUSPENSIÓN",
  "TABLETA",
  "TABLETA MASTICABLE",
  "TABLETA RECUBIERTA",
  "DISPOSITIVO",
  "OTRO",
];

export const tiposMedicamento: string[] = [
  "GENERICO",
  "DE MARCA",
  "ANTIFUNGICO",
  "SIMPATICOMIMETICO",
  "TRANQUILIZANTE",
  "VASODILATADOR",
  "VITAMINA",
  "MINERAL",
  "SUPLEMENTO",
  "HOMEOPATICO",
  "FITOTERAPICO",
  "DISPOSITIVO",
  "MATERIAL",
  "OTRO",
];
