export const kpisMonitoreos = [
  {
    id: 1,
    label: "MONITOREOS\nDEL AÑO",
    value: "6",
    sub: "de 8 programados",
    icon: "fa-heart-pulse",
    iconBg: "bg-[#e6f0ff]",
    iconColor: "text-brand",
  },
  {
    id: 2,
    label: "AGENTES QUE EXCEDEN\nLMP",
    value: "3",
    sub: "ruido, polvo, vibración",
    icon: "fa-head-side-mask",
    iconBg: "bg-risk-salmon/15",
    iconColor: "text-risk-salmon",
  },
  {
    id: 3,
    label: "RESULTADOS\nOBSERVADOS",
    value: "2",
    sub: "psicosocial y ergonómico",
    icon: "fa-person-circle-exclamation",
    iconBg: "bg-success/15",
    iconColor: "text-success-dark",
  },
  {
    id: 4,
    label: "CONFORMES",
    value: "1",
    sub: "",
    icon: "fa-person-circle-check",
    iconBg: "bg-risk-red/10",
    iconColor: "text-risk-red",
  },
] as const;

export const resultadosMonitoreo = [
  {
    id: 1,
    agente: "Ruido ocupacional",
    tipo: "Higiénico",
    area: "Mina – Perforación",
    fecha: "2026-05-08",
    resultado: "94.2 dBA",
    lmp: "85 dBA",
    estado: "EXCEDE",
    estadoClass: "bg-risk-red/15 text-risk-red",
  },
  {
    id: 2,
    agente: "Polvo respirable (sílice)",
    tipo: "Higiénico",
    area: "Planta – Chancado",
    fecha: "2026-04-27",
    resultado: "0.09 mg/m³",
    lmp: "0.05 mg/m³",
    estado: "EXCEDE",
    estadoClass: "bg-risk-red/15 text-risk-red",
  },
  {
    id: 3,
    agente: "Iluminación",
    tipo: "Higiénico",
    area: "Taller mantenimiento",
    fecha: "2026-04-11",
    resultado: "410 lux",
    lmp: "300 lux",
    estado: "CONFORME",
    estadoClass: "bg-success/15 text-success-dark",
  },
  {
    id: 4,
    agente: "Vibración cuerpo entero",
    tipo: "Higiénico",
    area: "Acarreo",
    fecha: "2026-03-30",
    resultado: "0.61 m/s²",
    lmp: "0.5 m/s²",
    estado: "EXCEDE",
    estadoClass: "bg-risk-red/15 text-risk-red",
  },
  {
    id: 5,
    agente: "Factores psicosociales",
    tipo: "Psicosocial",
    area: "Toda la operación",
    fecha: "2026-03-02",
    resultado: "Riesgo medio",
    lmp: "Riesgo bajo",
    estado: "OBSERVADO",
    estadoClass: "bg-risk-salmon/15 text-risk-salmon",
  },
] as const;
