export const kpisPlanAnual = [
  {
    id: 1,
    label: "ACTIVIDADES\nDEL PLAN",
    value: "8",
    sub: "3 cerradas · 4 en curso",
    icon: "fa-file-circle-plus",
    iconBg: "bg-[#e6f0ff]",
    iconColor: "text-brand",
  },
  {
    id: 2,
    label: "CUMPLIMIENTO\nACUMULADO",
    value: "78%",
    sub: "meta trimestral 85%",
    icon: "fa-file-shield",
    iconBg: "bg-risk-salmon/15",
    iconColor: "text-risk-salmon",
  },
  {
    id: 3,
    label: "INVERSIÓN\nPROGRAMADA",
    value: "S/ 293,900",
    sub: "ejecutado 61%",
    icon: "fa-coins",
    iconBg: "bg-success/15",
    iconColor: "text-success-dark",
  },
  {
    id: 4,
    label: "ACTIVIDADES EN RIESGO\nCUMPLIMIENTO",
    value: "2",
    sub: "requieren replanificación",
    icon: "fa-triangle-exclamation",
    iconBg: "bg-risk-red/10",
    iconColor: "text-risk-red",
  },
] as const;

export const actividadesPlan = [
  {
    id: 1,
    actividad: "Estudio de línea base y validación IA",
    responsable: "SST + CUIDDA",
    trimestre: "T1",
    inversion: "S/ 12,000",
    estado: "CERRADO",
    estadoClass: "bg-success/15 text-success-dark",
  },
  {
    id: 2,
    actividad: "EMO periódico – Mina (620 trabajadores)",
    responsable: "Lucemedic",
    trimestre: "T1–T2",
    inversion: "S/ 186,000",
    estado: "EN CURSO",
    estadoClass: "bg-violet/15 text-violet",
  },
  {
    id: 3,
    actividad: "Actualización matriz IPERC por puesto",
    responsable: "SST",
    trimestre: "T2",
    inversion: "S/ 8,500",
    estado: "EN CURSO",
    estadoClass: "bg-violet/15 text-violet",
  },
  {
    id: 4,
    actividad: "Monitoreo higiénico ocupacional anual",
    responsable: "Tercero acreditado",
    trimestre: "T2",
    inversion: "S/ 34,000",
    estado: "EN CURSO",
    estadoClass: "bg-violet/15 text-violet",
  },
  {
    id: 5,
    actividad: "Programa de conservación auditiva",
    responsable: "Médico ocupacional",
    trimestre: "T2–T4",
    inversion: "S/ 22,400",
    estado: "PROGRAMADO",
    estadoClass: "bg-muted-20 text-muted",
  },
] as const;

export const avanceMensual = [
  { mes: "Enero", plan: 62, ejec: 58 },
  { mes: "Febrero", plan: 90, ejec: 60 },
  { mes: "Marzo", plan: 80, ejec: 70 },
  { mes: "Abril", plan: 90, ejec: 30 },
  { mes: "Mayo", plan: 80, ejec: 75 },
  { mes: "Junio", plan: 95, ejec: 60 },
] as const;
