export const kpisProgramas = [
  {
    id: 1,
    label: "PROGRAMAS\nACTIVOS",
    value: "8",
    sub: "4 ocup. · 3 prev.",
    icon: "fa-file-circle-check",
    iconBg: "bg-[#e6f0ff]",
    iconColor: "text-brand",
  },
  {
    id: 2,
    label: "POBLACIÓN\nCUBIERTA",
    value: "1,284",
    sub: "100% de la vigilancia",
    icon: "fa-users",
    iconBg: "bg-risk-salmon/15",
    iconColor: "text-risk-salmon",
  },
  {
    id: 3,
    label: "AVANCE\nPROMEDIO",
    value: "68%",
    sub: "+6 pts vs. trimestre ant.",
    icon: "fa-chart-line",
    iconBg: "bg-success/15",
    iconColor: "text-success-dark",
  },
  {
    id: 4,
    label: "ACTIVIDADES\nATRASADAS",
    value: "2",
    sub: "salud mental y población sensible",
    icon: "fa-user-clock",
    iconBg: "bg-risk-red/10",
    iconColor: "text-risk-red",
  },
] as const;

export const tabsProgramas = [
  "TODOS",
  "OCUPACIONAL",
  "PREVENTIVO",
  "SUBPROGRAMA",
] as const;

export const programasCards = [
  {
    id: 1,
    titulo: "Conservación auditiva",
    responsable: "Dr. A. Manrique",
    categoria: "OCUPACIONAL",
    categoriaClass: "bg-violet/15 text-violet",
    avance: 82,
    trabajadores: "218 trabajadores",
    actividades: "10/12 actividades",
    grupos: ["G2", "G3"],
    barColor: "bg-violet",
  },
  {
    id: 2,
    titulo: "Protección respiratoria",
    responsable: "Dra. L. Peña",
    categoria: "OCUPACIONAL",
    categoriaClass: "bg-violet/15 text-violet",
    avance: 64,
    trabajadores: "198 trabajadores",
    actividades: "9/14 actividades",
    grupos: ["G2", "G3"],
    barColor: "bg-violet",
  },
  {
    id: 3,
    titulo: "Ergonomía y espalda sana",
    responsable: "Lic. M. Solís",
    categoria: "OCUPACIONAL",
    categoriaClass: "bg-violet/15 text-violet",
    avance: 71,
    trabajadores: "230 trabajadores",
    actividades: "7/10 actividades",
    grupos: ["G1", "G2", "G3"],
    barColor: "bg-violet",
  },
  {
    id: 4,
    titulo: "Salud mental y fatiga",
    responsable: "Ps. C. Rivas",
    categoria: "OCUPACIONAL",
    categoriaClass: "bg-violet/15 text-violet",
    avance: 55,
    trabajadores: "421 trabajadores",
    actividades: "9/16 actividades",
    grupos: ["G1", "G2", "G3"],
    barColor: "bg-violet",
  },
  {
    id: 5,
    titulo: "Cardiometabólico",
    responsable: "Dr. J. Núñez",
    categoria: "PREVENTIVO",
    categoriaClass: "bg-success/15 text-success-dark",
    avance: 68,
    trabajadores: "356 trabajadores",
    actividades: "6/9 actividades",
    grupos: ["G2", "G3"],
    barColor: "bg-success",
  },
  {
    id: 6,
    titulo: "Nutrición y peso saludable",
    responsable: "Nut. P. Torres",
    categoria: "PREVENTIVO",
    categoriaClass: "bg-success/15 text-success-dark",
    avance: 74,
    trabajadores: "298 trabajadores",
    actividades: "6/8 actividades",
    grupos: ["G1", "G2"],
    barColor: "bg-success",
  },
  {
    id: 7,
    titulo: "Salud visual",
    responsable: "Dra. L. Peña",
    categoria: "PREVENTIVO",
    categoriaClass: "bg-success/15 text-success-dark",
    avance: 88,
    trabajadores: "142 trabajadores",
    actividades: "5/6 actividades",
    grupos: ["G1", "G2"],
    barColor: "bg-success",
  },
  {
    id: 8,
    titulo: "Población sensible (subprograma)",
    responsable: "Dr. A. Manrique",
    categoria: "SUBPROGRAMA",
    categoriaClass: "bg-risk-salmon/15 text-risk-salmon",
    avance: 41,
    trabajadores: "47 trabajadores",
    actividades: "4/11 actividades",
    grupos: ["G3"],
    barColor: "bg-risk-salmon",
  },
] as const;

export const resultadosMonitoreoProgramas = [
  {
    id: 1,
    programa: "Conservación auditiva",
    actividad: "Audiometría tonal semestral (G2/G3)",
    responsable: "Lucemedic",
    vence: "2026-09-15",
    estado: "EN CURSO",
    estadoClass: "bg-violet/15 text-violet",
  },
  {
    id: 2,
    programa: "Conservación auditiva",
    actividad: "Prueba de ajuste de protector auditivo",
    responsable: "SST",
    vence: "2026-08-30",
    estado: "EN CURSO",
    estadoClass: "bg-violet/15 text-violet",
  },
  {
    id: 3,
    programa: "Protección respiratoria",
    actividad: "Espirometría y RX OIT a expuestos a sílice",
    responsable: "Lucemedic",
    vence: "2026-10-10",
    estado: "PROGRAMADO",
    estadoClass: "bg-muted-20 text-muted",
  },
  {
    id: 4,
    programa: "Ergonomía y espalda sana",
    actividad: "Evaluación REBA en mantenimiento",
    responsable: "Lic. M. Solís",
    vence: "2026-08-22",
    estado: "EN CURSO",
    estadoClass: "bg-violet/15 text-violet",
  },
  {
    id: 5,
    programa: "Salud mental y fatiga",
    actividad: "Tamizaje de fatiga en turnos rotativos",
    responsable: "Ps. C. Rivas",
    vence: "2026-09-05",
    estado: "ATRASADO",
    estadoClass: "bg-risk-salmon/15 text-risk-salmon",
  },
  {
    id: 6,
    programa: "Cardiometabólico",
    actividad: "Control de presión y perfil lipídico",
    responsable: "Dr. J. Núñez",
    vence: "2026-09-28",
    estado: "PROGRAMADO",
    estadoClass: "bg-muted-20 text-muted",
  },
  {
    id: 7,
    programa: "Población sensible (subprograma)",
    actividad: "Plan individual de 47 casos sensibles",
    responsable: "Dr. A. Manrique",
    vence: "2026-08-29",
    estado: "ATRASADO",
    estadoClass: "bg-risk-salmon/15 text-risk-salmon",
  },
  {
    id: 8,
    programa: "Nutrición y peso saludable",
    actividad: "Seguimiento nutricional de trabajadores en riesgo",
    responsable: "Nut. P. Torres",
    vence: "2026-09-12",
    estado: "PROGRAMADO",
    estadoClass: "bg-muted-20 text-muted",
  },
  {
    id: 9,
    programa: "Salud visual",
    actividad: "Tamizaje visual ocupacional",
    responsable: "Dra. L. Peña",
    vence: "2026-09-20",
    estado: "PROGRAMADO",
    estadoClass: "bg-muted-20 text-muted",
  },
] as const;
